force-app/main/default/objects/Validation_Criteria__mdt/Validation_Criteria__mdt.object-meta.xml
<CustomObject>
    <description>This will hold the specific criteria that needs to be applied for the validation to flag</description>
    <label>Validation Criteria</label>
    <pluralLabel>Validation Criterion</pluralLabel>
</CustomObject>

force-app/main/default/objects/Validation_Criteria__mdt/fields/Filter_Value__c.field-meta.xml
<CustomField>
    <fullName>Filter_Value__c</fullName>
    <description>This will be the filter value used in the criteria, this should be in string format that is parsable by Apex (eg date formats as YYYY-MM-DD)</description>
    <label>Filter Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Validation_Criteria__mdt/fields/Index__c.field-meta.xml
<CustomField>
    <fullName>Index__c</fullName>
    <description>The index that this rule should be evaluated at</description>
    <label>Index</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Validation_Criteria__mdt/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <description>Which operator to apply to the condition before running it</description>
    <label>Operator</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Equal</fullName>
                <default>true</default>
                <label>Equal</label>
            </value>
            <value>
                <fullName>Not Equal</fullName>
            </value>
            <value>
                <fullName>Contains</fullName>
            </value>
            <value>
                <fullName>Does Not Contain</fullName>
            </value>
            <value>
                <fullName>Starts With</fullName>
            </value>
            <value>
                <fullName>Ends With</fullName>
            </value>
            <value>
                <fullName>Less Than</fullName>
            </value>
            <value>
                <fullName>Less Or Equal</fullName>
            </value>
            <value>
                <fullName>Greater Than</fullName>
            </value>
            <value>
                <fullName>Greater Or Equal</fullName>
            </value>
            <value>
                <fullName>Includes</fullName>
            </value>
            <value>
                <fullName>Excludes</fullName>
            </value>
            <value>
                <fullName>Within</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Validation_Criteria__mdt/fields/Validated_Field__c.field-meta.xml
<CustomField>
    <fullName>Validated_Field__c</fullName>
    <description>The field that should be eveluated against the criteria</description>
    <label>Validated Field</label>
    <metadataRelationshipControllingField>Validation_Criteria__mdt.Validated_Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Validation_Criterion</relationshipLabel>
    <relationshipName>Validation_Criterion</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Validation_Criteria__mdt/fields/Validated_Object__c.field-meta.xml
<CustomField>
    <fullName>Validated_Object__c</fullName>
    <description>The that should be validated against</description>
    <label>Validated Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Validation_Criterion</relationshipLabel>
    <relationshipName>Validation_Criterion</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Validation_Criteria__mdt/fields/Validation_Rule__c.field-meta.xml
<CustomField>
    <fullName>Validation_Rule__c</fullName>
    <description>Parent validation that should be applief for this validation rule</description>
    <label>Validation Rule</label>
    <referenceTo>Validation_Rule__mdt</referenceTo>
    <relationshipLabel>Validation Criterion</relationshipLabel>
    <relationshipName>Validation_Criterion</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Validation_Rule__mdt/Validation_Rule__mdt.object-meta.xml
<CustomObject>
    <description>This will be the top level definition for a validation rule, if the criteria defined are then hit a validation error message will fire</description>
    <label>Validation Rule</label>
    <pluralLabel>Validation Rules</pluralLabel>
</CustomObject>

force-app/main/default/objects/Validation_Rule__mdt/fields/Conditional_Logic__c.field-meta.xml
<CustomField>
    <fullName>Conditional_Logic__c</fullName>
    <description>The logic the conditions should perform as, for example (1 and 2 or 3)</description>
    <label>Conditional Logic</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Validation_Rule__mdt/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>The error message that should be applied if the criteria is hit</description>
    <label>Error Message</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Validation_Rule__mdt/fields/Validated_Object__c.field-meta.xml
<CustomField>
    <fullName>Validated_Object__c</fullName>
    <description>The object that should be validated for this validation rule, this should be matched on all the criterion records</description>
    <label>Validated Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Validation_Rules</relationshipLabel>
    <relationshipName>Validation_Rules</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/ValidationEngine.cls
public with sharing class ValidationEngine {

    private static final Map<String, List<ValidationRule>> VALIDATION_RULES_BY_OBEJCT = new Map<String, List<ValidationRule>>();
    private final String objectApiName;

    public ValidationEngine(SObjectType objectType) {
        objectApiName = objectType.getDescribe().getName();
    }

    public void validateRecords(List<SObject> records) {
        for (ValidationRule rule : getValidationRules(objectApiName)) {
            for (SObject record: records) {
                rule.validateRecord(record);
            }
        }
    }

    private List<ValidationRule> getValidationRules(String objectApiName) {
        if (!VALIDATION_RULES_BY_OBEJCT.containsKey(objectApiName)) {
            List<ValidationRule> validationRules = new List<ValidationRule>();
            for (Validation_Rule__mdt validationMetadata : [
                    SELECT Error_Message__c, Conditional_Logic__c,
                        Validated_Object__r.QualifiedApiName, (
                        SELECT Index__c, Filter_Value__c, Operator__c,
                            Validated_Field__r.QualifiedApiName
                        FROM Validation_Criterion__r
                    ) FROM Validation_Rule__mdt
                    WHERE Validated_Object__r.QualifiedApiName = :objectApiName
            ]) {
                validationRules.add(
                    new ValidationRule(validationMetadata)
                );
            }
            VALIDATION_RULES_BY_OBEJCT.put(
                objectApiName, validationRules
            );
        }
        return VALIDATION_RULES_BY_OBEJCT.get(objectApiName);
    }

    public class ValidationRule {
        private final String objectApiName;
        private ConditionInterpreter criteria;
        private final String errorMessage;
        public ValidationRule(Validation_Rule__mdt validationMetadata) {
            this.objectApiName = validationMetadata.Validated_Object__r.QualifiedApiName;
            errorMessage = validationMetadata.Error_Message__c;
            criteria = new ConditionInterpreter(
                validationMetadata.Conditional_Logic__c,
                getConditions(validationMetadata.Validation_Criterion__r)
            );
        }

        public void validateRecord(SObject recordToValidate) {
            if (criteria.isMatch(recordToValidate)) {
                recordToValidate.addError(errorMessage);
            }
        }

        private Map<Integer, FieldCondition> getConditions(List<Validation_Criteria__mdt> criterion) {
            Map<Integer, FieldCondition> conditions = new Map<Integer, FieldCondition>();
            for (Validation_Criteria__mdt criteria : criterion) {
                SchemaFacade schema = SchemaFacade.getInstance();
                DescribeFieldResult field = schema.getFieldDescribe(objectApiName, criteria.Validated_Field__r.QualifiedApiName);
                Parsable parser = new DisplayTypeParser(field.getType());
                conditions.put(
                    Integer.valueOf(criteria.Index__c),
                    new FieldCondition(
                        field.getSObjectField(),
                        criteria.Operator__c,
                        parser.parse(criteria.Filter_Value__c)
                    )
                );
            }
            return conditions;
        }
    }
}